Repository AY2223S1-CS2103T-W16-2/tp, pull requests merged in 2022-09, with the labels that each got.

#34 Add Ui mockup
  docs/images/Ui.png
Labels: documentation

#67 Add profile picture
  docs/images/ferusel.jpg
Labels: weekly deliverables

#64 Add PPP skeleton
  docs/team/ferusel.md
Labels: weekly deliverables

#77 Add Commands for list, find and bye in UG
  docs/UserGuide.md
Labels: weekly deliverables

#78 Add Acknowledgments in README
  README.md
Labels: documentation, weekly deliverables

#57 Add NFRs to DG
  docs/DeveloperGuide.md
Labels: weekly deliverables

#81 Add bryanljx PPP skeleton
  docs/team/bryanljx.md
Labels: weekly deliverables

#83 Update AboutUs
  docs/AboutUs.md
  docs/images/bryanljx.png
Labels: weekly deliverables

#88 Update UG
  docs/UserGuide.md
Labels: weekly deliverables

#87 Add Glossary, UC3, UC4 to Developer Guide
  docs/DeveloperGuide.md
Labels: documentation, weekly deliverables

#82 Add User Guide section
  docs/UserGuide.md
Labels: documentation, weekly deliverables

#93 Add skeletal "user profile" section to DG
  docs/DeveloperGuide.md
Labels: weekly deliverables

#96 Add image for aboutUs page
  docs/images/yixiann.png
Labels: weekly deliverables
