Repository AY2223S1-CS2103T-W16-2/tp, pull requests merged in 2022-11, with the labels that each got.

#434 Fix getColor for tags
  src/main/java/seedu/foodrem/views/TagView.java
Labels: command.tags, bug

#419 Reformat DG User Stories Table
  docs/_dg/UserStories.md
Labels: documentation.DeveloperGuide

#432 Fix broken glossary term for expiry date and broken link for flags
  docs/_glossary/ExpiryDate.md
  docs/_ug/KeyDefinitions.md
Labels: documentation.UserGuide, bug

#428 Optimise styles for PDF layout
  .gitignore
  docs/UserGuide.md
  docs/_dg/implementations/ItemFeatures.md
  docs/_glossary/BOUGHT_DATE.md
  docs/_glossary/COMMAND_WORD.md
  docs/_glossary/EXPIRY_DATE.md
  docs/_glossary/INDEX.md
  docs/_glossary/ITEM_NAME.md
  docs/_glossary/KEYWORD.md
  docs/_glossary/PRICE.md
  docs/_glossary/QUANTITY2.md
  docs/_glossary/REMARKS.md
  docs/_glossary/TAG_NAME.md
  docs/_glossary/UNIT.md
  docs/_includes/custom-head.html
  docs/_includes/glossary.md
  docs/_includes/toc.md
  docs/_sass/admonitions.scss
  docs/_sass/foodrem.scss
  docs/_sass/minima/skins/classic.scss
  docs/_sass/pdf.scss
  docs/_ug/HowToUseUserGuide.md
  docs/_ug/KeyDefinitions.md
  docs/_ug/Layout.md
  docs/_ug/commands/GeneralCommands.md
  docs/_ug/commands/ItemCommands.md
  docs/_ug/commands/StatisticsCommands.md
  docs/_ug/commands/TagCommands.md
  docs/assets/css/style.scss
  docs/images/FoodRemFullUi.png
  docs/images/Ui.png
Labels: type.enhancement, priority.High, documentation.UserGuide, documentation.DeveloperGuide, documentation

#439 Add PPP checking workflow
  .github/workflows/check-ppp-edited.yml
  cli-test/check-ppp-is-complete.sh
  docs/team/richdom2185.md
Labels: type.enhancement, priority.Medium

#459 Update PPP for ferusel
  docs/team/ferusel.md
Labels: deliverables.Individual

#450 Ensure we cannot create an item with bought date after expiry date
  docs/_ug/commands/ItemCommands.md
  src/main/java/seedu/foodrem/logic/commands/statscommands/StatsCommand.java
  src/main/java/seedu/foodrem/model/item/Item.java
  src/main/java/seedu/foodrem/model/item/ItemBoughtDate.java
  src/main/java/seedu/foodrem/model/item/ItemDate.java
  src/main/java/seedu/foodrem/model/item/ItemExpiryDate.java
  src/main/java/seedu/foodrem/model/item/itemcomparators/ItemCostComparator.java
  src/main/java/seedu/foodrem/model/item/itemcomparators/ItemValueComparator.java
  src/main/java/seedu/foodrem/model/item/itemvalidators/ItemBoughtDateValidator.java
  src/main/java/seedu/foodrem/model/item/itemvalidators/ItemExpiryDateValidator.java
  src/main/java/seedu/foodrem/model/util/SampleDataUtil.java
  src/main/java/seedu/foodrem/views/ItemView.java
  src/test/java/seedu/foodrem/testutil/ItemsToSort.java
Labels: bug

#461 Fix website index
  docs/index.md
Labels: documentation, bug

#463 Update personal PPP
  docs/_ug/Installation.md
  docs/team/bryanljx.md
Labels: deliverables.Individual

#468 Remove code duplication and update PPP
  README.md
  docs/_data/foodrem.yml
  docs/_data/projects.yml
  docs/_dg/Acknowledgements.md
  docs/_layouts/ppp.html
  docs/_ug/About.md
  docs/_ug/Acknowledgements.md
  docs/team/bryanljx.md
  docs/team/eugenetanwl3881.md
  docs/team/ferusel.md
  docs/team/richdom2185.md
  docs/team/yixiann.md
Labels: documentation

#466 Fix error message that says "the FoodRem"
  src/main/java/seedu/foodrem/logic/Logic.java
  src/main/java/seedu/foodrem/logic/commands/itemcommands/EditCommand.java
  src/main/java/seedu/foodrem/logic/commands/itemcommands/FilterTagCommand.java
  src/main/java/seedu/foodrem/logic/commands/tagcommands/DeleteTagCommand.java
  src/main/java/seedu/foodrem/logic/commands/tagcommands/RenameTagCommand.java
  src/main/java/seedu/foodrem/model/FoodRem.java
  src/main/java/seedu/foodrem/model/Model.java
  src/main/java/seedu/foodrem/model/tag/TagName.java
  src/test/java/seedu/foodrem/logic/commands/itemcommands/FilterTagCommandTest.java
  src/test/java/seedu/foodrem/logic/commands/tagcommands/DeleteTagCommandTest.java
  src/test/java/seedu/foodrem/logic/commands/tagcommands/RenameTagCommandTest.java
Labels: bug

#433 Improve front matters as per comments in DG peer review
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/_dg/AboutDG.md
  docs/_dg/Architecture.md
  docs/_dg/Design.md
  docs/_dg/Effort.md
  docs/_dg/HowToUseDeveloperGuide.md
  docs/_dg/Implementation.md
  docs/_dg/InstructionsForManualTesting.md
  docs/_dg/LogicComponent.md
  docs/_dg/ModelComponent.md
  docs/_dg/StorageComponent.md
  docs/_dg/UIComponent.md
  docs/_ug/AboutUG.md
  docs/_ug/AdmonitionBoxes.md
  docs/_ug/Commands.md
  docs/_ug/HowToUseUserGuide.md
Labels: documentation.DeveloperGuide

#465 Fix bought date to be in future in test cases
  src/main/java/seedu/foodrem/model/item/Item.java
  src/main/java/seedu/foodrem/model/item/ItemDate.java
  src/main/java/seedu/foodrem/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableFoodRemTest/duplicateItemFoodRem.json
  src/test/data/JsonSerializableFoodRemTest/duplicateTagFoodRem.json
  src/test/data/JsonSerializableFoodRemTest/invalidItemFoodRem.json
  src/test/data/JsonSerializableFoodRemTest/invalidTagFoodRem.json
  src/test/data/JsonSerializableFoodRemTest/typicalFoodRem.json
  src/test/data/JsonSerializableFoodRemTest/typicalItemsFoodRem.json
  src/test/java/seedu/foodrem/logic/commands/CommandTestUtil.java
  src/test/java/seedu/foodrem/model/item/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/foodrem/storage/JsonAdaptedItemTest.java
  src/test/java/seedu/foodrem/testutil/TypicalItems.java
Labels: command.items, bug

#469 Minify HTML output
  docs/_layouts/compress.liquid
  docs/_layouts/default.html
Labels: type.enhancement, documentation

#467 Remove raw types
  src/main/java/seedu/foodrem/logic/LogicManager.java
  src/main/java/seedu/foodrem/logic/commands/Command.java
  src/main/java/seedu/foodrem/ui/CommandBox.java
  src/test/java/seedu/foodrem/logic/LogicManagerTest.java
Labels: type.enhancement

#511 Fix extra whitespace in autoglossary items
  docs/_includes/autoglossary.liquid
Labels: documentation.UserGuide, documentation.DeveloperGuide, documentation, bug

#510 Make PPP checking more lenient
  .github/workflows/check-ppp-edited.yml
  cli-test/ppp-checker/check-ppp-is-complete.sh
  cli-test/ppp-checker/check-ppp-is-present.sh
Labels: type.enhancement, documentation

#508 Auto build PDFs together with JAR file
  .github/workflows/build.yml
  .gitignore
  docs/.gitignore
  docs/Documentation.md
  docs/make-pdf.sh
Labels: type.enhancement, documentation.UserGuide, documentation.DeveloperGuide, documentation

#507 Add link checker
  .github/workflows/check-links.yml
  cli-test/linkchecker/.gitignore
  cli-test/linkchecker/check-links.js
  cli-test/linkchecker/package-lock.json
  cli-test/linkchecker/package.json
  cli-test/linkchecker/serve-and-check.py
Labels: type.enhancement, documentation.UserGuide, documentation.DeveloperGuide, documentation

#514 Fix PDF building script
  docs/make-pdf.sh
Labels: type.enhancement, priority.Medium, bug

#505 Fill in all commands for manual testing instructions
  docs/_dg/InstructionsForManualTesting.md
Labels: documentation.DeveloperGuide

#513 Add and style PR badge for PPP
  docs/_includes/icons/git-merge.svg
  docs/_includes/ppp-badges.liquid
  docs/_layouts/ppp.html
  docs/_sass/ppp.scss
  docs/assets/css/style.scss
  docs/team/bryanljx.md
  docs/team/eugenetanwl3881.md
  docs/team/ferusel.md
  docs/team/richdom2185.md
  docs/team/yixiann.md
Labels: type.enhancement, documentation

#503 Add Effort section of DG
  docs/_dg/Effort.md
Labels: documentation.DeveloperGuide

#464 Update DG Implementation for Tag Features
  docs/_dg/implementations/TagFeatures.md
  docs/diagrams/NewTagSequenceDiagram.puml
  docs/diagrams/TagItemActivityDiagram.puml
  docs/diagrams/TagSequenceDiagram.puml
  docs/images/NewTagSequenceDiagram.png
  docs/images/TagItemActivityDiagram.png
  docs/images/TagSequenceDiagram.png
  src/main/java/seedu/foodrem/logic/parser/tagcommandparser/RenameTagCommandParser.java
Labels: deliverables.Individual, documentation.DeveloperGuide

#516 Update UG Troubleshooting
  docs/_ug/Troubleshooting.md
Labels: documentation.UserGuide, documentation

#376 Set height of text area to be 450
  src/main/java/seedu/foodrem/views/StringView.java
Labels: bug

#519 Fix minor errors
  src/main/java/seedu/foodrem/commons/enums/CommandType.java
  src/main/java/seedu/foodrem/logic/commands/generalcommands/HelpCommand.java
  src/main/java/seedu/foodrem/views/StatsView.java
  src/test/java/seedu/foodrem/logic/commands/generalcommands/HelpCommandTest.java
  src/test/java/seedu/foodrem/logic/parser/generalcommandparser/HelpCommandParserTest.java
Labels: bug

#527 Add DG help command sequence diagram and activity diagram
  docs/_dg/implementations/GeneralFeatures.md
  docs/diagrams/HelpActivityDiagram.puml
  docs/diagrams/HelpSequenceDiagram.puml
  docs/images/HelpActivityDiagram.png
  docs/images/HelpSequenceDiagram.png
  docs/team/yixiann.md
Labels: documentation.DeveloperGuide, documentation

#528 Update Developer Guide
  docs/_dg/implementations/ItemFeatures.md
  docs/_dg/implementations/StatisticsFeatures.md
  docs/diagrams/EditItemActivityDiagram.puml
  docs/diagrams/EditItemSequenceDiagram.puml
  docs/diagrams/NewItemActivityDiagram.puml
  docs/diagrams/NewItemSequenceDiagram.puml
  docs/diagrams/SortItemsSequenceDiagram.puml
  docs/images/EditItemActivityDiagram.png
  docs/images/EditItemSequenceDiagram.png
  docs/images/NewItemActivityDiagram.png
  docs/images/NewItemSequenceDiagram.png
  docs/images/SortItemsSequenceDiagram.png
Labels: documentation.DeveloperGuide

#529 Add and style Issues badge for PPP
  docs/_includes/icons/git-merge.svg
  docs/_includes/icons/issue-closed.svg
  docs/_includes/ppp-badges.liquid
  docs/_sass/ppp.scss
  docs/team/yixiann.md
Labels: type.enhancement, documentation

#524 Fix grammar in DG
  docs/DeveloperGuide.md
  docs/_data/foodrem.yml
  docs/_dg/AboutDG.md
  docs/_dg/Architecture.md
  docs/_dg/Design.md
  docs/_dg/Effort.md
  docs/_dg/HowToUseDeveloperGuide.md
  docs/_dg/InstructionsForManualTesting.md
  docs/_dg/LogicComponent.md
  docs/_dg/ModelComponent.md
  docs/_dg/NFRs.md
  docs/_dg/UIComponent.md
  docs/_dg/implementations/ItemFeatures.md
Labels: documentation.DeveloperGuide, documentation

#531 Add general section for items and Inc and Dec features
  docs/_dg/AboutDG.md
  docs/_dg/Architecture.md
  docs/_dg/Design.md
  docs/_dg/implementations/GeneralFeatures.md
  docs/_dg/implementations/ItemFeatures.md
  docs/diagrams/DecrementActivityDiagram.puml
  docs/diagrams/ItemClassDiagram.puml
  docs/diagrams/ItemFieldClassDiagram.puml
  docs/images/DecrementActivityDiagram.png
  docs/images/ItemClassDiagram.png
  docs/images/ItemFieldClassDiagram.png
Labels: documentation.DeveloperGuide, documentation

#530 Small fixes to PPP
  docs/team/eugenetanwl3881.md
Labels: documentation

#535 Update UG for remarks bug
  docs/_ug/commands/ItemCommands.md
Labels: documentation.UserGuide, documentation

#536 Update PPP for ferusel
  docs/team/ferusel.md
Labels: deliverables.Individual

#525 Update documentation
  docs/UserGuide.md
  docs/_data/constraints.yml
  docs/_data/foodrem.yml
  docs/_dg/Architecture.md
  docs/_dg/HowToUseDeveloperGuide.md
  docs/_dg/InstructionsForManualTesting.md
  docs/_dg/LogicComponent.md
  docs/_dg/UserStories.md
  docs/_dg/implementations/ItemFeatures.md
  docs/_dg/implementations/StatisticsFeatures.md
  docs/_glossary/Argument.md
  docs/_glossary/HelpWindow.md
  docs/_glossary/MSS.md
  docs/_includes/autoglossary.liquid
  docs/_sass/foodrem.scss
  docs/_sass/pdf.scss
  docs/_ug/AboutUG.md
  docs/_ug/KeyDefinitions.md
  docs/_ug/Layout.md
  docs/_ug/TryingFirstCommand.md
  docs/_ug/commands/GeneralCommands.md
  docs/_ug/commands/ItemCommands.md
  docs/_ug/commands/StatisticsCommands.md
  docs/_ug/commands/TagCommands.md
  docs/images/CommandInputBox.png
  docs/images/CommandOutputBox.png
  docs/images/HelpWindow.png
  docs/images/ItemImage.png
  docs/images/ItemListBox.png
  docs/images/UiAnnotated.png
  docs/images/generalCommands/commandOutputBox/reset.png
  docs/team/richdom2185.md
Labels: deliverables.Individual, documentation.UserGuide, documentation.DeveloperGuide, documentation

#515 Auto glossary for UG
  docs/_glossary/URL.md
  docs/_ug/Commands.md
  docs/_ug/Features.md
  docs/_ug/Layout.md
  docs/_ug/QuickstartGuide.md
  docs/_ug/TryingFirstCommand.md
  docs/_ug/commands/GeneralCommands.md
  docs/_ug/commands/StatisticsCommands.md
Labels: documentation.UserGuide, documentation

#541 Fix PDF spacing in UG
  docs/_ug/KeyDefinitions.md
  docs/_ug/commands/ItemCommands.md
Labels: documentation.UserGuide, documentation

#539 Add warning for find command
  docs/_ug/commands/ItemCommands.md
Labels: documentation.UserGuide

#537 Force window size to have min height and width
  src/main/resources/view/MainWindow.fxml
Labels: bug

#547 Fix grammar
  src/main/java/seedu/foodrem/commons/core/Messages.java
  src/main/java/seedu/foodrem/logic/commands/itemcommands/FilterTagCommand.java
  src/main/java/seedu/foodrem/logic/commands/itemcommands/FindCommand.java
  src/main/java/seedu/foodrem/logic/commands/itemcommands/SortCommand.java
  src/test/java/seedu/foodrem/logic/commands/itemcommands/FindCommandTest.java
Labels: bug

#546 Fix storage diagram
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/foodrem/storage/JsonSerializableFoodRem.java
Labels: documentation.DeveloperGuide, documentation, bug

#548 Fix about us page
  docs/AboutUs.md
Labels: bug

#551 Update DG with UI Implementation
  docs/_dg/AboutDG.md
  docs/_dg/Effort.md
  docs/_dg/Implementation.md
  docs/_dg/UIComponent.md
  docs/_dg/implementations/GeneralFeatures.md
  docs/_dg/implementations/UserInterface.md
  docs/_ug/TryingFirstCommand.md
  docs/diagrams/UIProposedClassDiagram.puml
  docs/diagrams/UISequenceDiagram.puml
  docs/images/UIProposedClassDiagram.png
  docs/images/UISequenceDiagram.png
  docs/team/ferusel.md
Labels: documentation.DeveloperGuide, documentation

#555 Fix DG UML diagrams
  docs/_dg/implementations/ItemFeatures.md
  docs/diagrams/NewItemActivityDiagram.puml
  docs/images/NewItemActivityDiagram.png
Labels: bug

#561 Update reuse section
  README.md
  copyright.txt
  docs/_data/foodrem.yml
  docs/_dg/Acknowledgements.md
  docs/_ug/Acknowledgements.md
  docs/index.md
Labels: documentation.UserGuide, documentation.DeveloperGuide, documentation
